M48
; DRILL file {KiCad 7.0.7} date Wed May  8 11:13:57 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-08T11:13:57-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.0226Y-4.9026
X4.1309Y-4.9026
T2
X6.4518Y-2.4173
X6.4518Y-3.5984
T0
M30
